=== SoulApps/CrossPlatformLearning/Primero/Lenguajes de marcas/XML/Segundo/Ejercicio02/Peliculas.dtd
<!ELEMENT peliculas (pelicula)>
 <!ELEMENT pelicula (titulo, titulo_original?, director, duracion, genero, sinopsis, clasificacion?, web?, cartel?, fecha, reparto)>
 <!ELEMENT titulo (#PCDATA)>
 <!ELEMENT titulo_original (#PCDATA)>
 <!ELEMENT director (#PCDATA)>
 <!ELEMENT duracion (#PCDATA)>
 <!ELEMENT genero (#PCDATA)>
 <!ELEMENT sinopsis (#PCDATA)>
 <!ELEMENT clasificacion EMPTY>
 <!ELEMENT web (#PCDATA)>
 <!ELEMENT cartel (#PCDATA)>
 <!ELEMENT fecha (#PCDATA)>
 <!ELEMENT reparto (actor)>
 <!ELEMENT actor (protagonista+,secundario*)>
 <!ELEMENT protagonista (#PCDATA)>
 <!ELEMENT secundario (#PCDATA)>
 
 <!ATTLIST pelicula pais(españa|extranjero) "españa" #REQUIRED
 <!ATTLIST pelicula duracion CDATA "">
 <!ATTLIST pelicula año CDATA "2003">
 <!ATTLIST clasificacion edad(tp|8|12|16|18)#REQUIRED>

=== SoulApps/CrossPlatformLearning/Primero/Lenguajes de marcas/XML/Segundo/Ejercicio02/Peliculas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE PELICULAS SYSTEM "peliculas.dtd">

<peliculas>
	<pelicula pais="" duracion="">
		<titulo></titulo>
		<titulo_original></titulo_original>
		<director></director>
		<duracion></duracion>
		<genero></genero>
		<sinopsis></sinopsis>
		<clasificacion edad=""></clasificacion>
		<web></web>
		<cartel></cartel>
		<fecha></fecha>
		<reparto>
			<actor>
				<nombre></nombre>
				<fecha_nacimiento></fecha_nacimiento>
			</actor>
		</reparto>
	</pelicula>
</peliculas>
